### ISSUE TITLE
Fatal error on first composer install

### ISSUE THREAD

**Issue by Rastusik** [phpro/grumphp#492]
| Q               | A
| --------------- | ---
| Version         | 0.14
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

When running composer install in a clean repository (no vendor folder exists yet), I'm getting this error:

```
Fatal error: Class 'Doctrine\Common\Collections\ArrayCollection' not found in /Users/rasta/DEV/BetterSerializer/vendor/phpro/grumphp/src/Collection/ProcessArgumentsCollection.php on line 8
```

This happens when running the `GrumPHP\\Composer\\DevelopmentIntegrator::integrate` composer post install command for the first time.
When running `composer install` for the second time, the error isn't there anymore. Which is kind of ok, but this thing breaks my Travis build.

I'm using the composer `--no-scripts` flag as a workaround for now.

**My configuration**
```yaml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    process_timeout: 600
    tasks:
      phpcs:
        standard: PSR2
        tab_width: 4
        whitelist_patterns: []
        encoding: ~
        ignore_patterns: []
        sniffs: []
        triggered_by: [php]
      phpcsfixer2:
        allow_risky: true
        cache_file: .php_cs.cache
        config: .php_cs
        using_cache: true
        config_contains_finder: false
        verbose: true
        diff: false
        triggered_by: [php]
      phplint: ~
      phpmd:
        exclude: []
        ruleset: ['dev/phpmd.ruleset.xml']
        triggered_by: [php]
      phpparser: ~
      phpstan:
        autoload_file: ~
        configuration: dev/phpstan.neon
        level: 7
        triggered_by: [php]
      phpunit: ~
      infection:
        threads: 2
        test_framework: phpunit
        only_covered: true
        configuration: infection.json
        min_msi: ~
        min_covered_msi: ~
        mutators: []
        triggered_by: [php]
      phpversion: ~
      securitychecker: ~
      shell: ~

```

My composer.json file (minimised to the bare minimum to reproduced the error):

```json
{
    "name": "whatever/whatever",
    "description": "whatever",
    "type": "library",
    "license": "MIT",
    "minimum-stability": "dev",
    "require": {
        "php": "^7.2"
    },
    "require-dev": {
        "doctrine/collections": "^1.5",
        "phpro/grumphp": "^v0.14"
    },

    "autoload": {
        "psr-4": {
            "BetterSerializer\\": "src/BetterSerializer/"
        }
    },

    "autoload-dev": {
        "psr-4": {
            "BetterSerializer\\": "tests/BetterSerializer/",
            "Integration\\": "tests/Integration/"
        }
    },

    "config": {
        "platform": {
            "php": "7.2"
        },
        "sort-packages": true
    }
}

```

**Steps to reproduce:**
```sh
# Generate empty folder
git clone https://github.com/better-serializer/better-serializer.git
cd better-serializer
git checkout faster_than_reflection
composer install -o --no-interaction  

```

**Result:**
```
Writing lock file
Generating optimized autoload files

Fatal error: Class 'Doctrine\Common\Collections\ArrayCollection' not found in /Users/rasta/DEV/BetterSerializer/vendor/phpro/grumphp/src/Collection/ProcessArgumentsCollection.php on line 8
```

**Comment by Landerstraeten** [comment]
@Rastusik, works fine for me

**Comment by Rastusik** [comment]
@Landerstraeten I'm sorry I forgot one step in the reproduction instructions. Could you please try one more time to see the problem? Thank you

**Comment by veewee** [comment]
Still works here with the new instructions on PHP 7.2.2.
Maybe PHP version or composer cache related?

**Comment by Rastusik** [comment]
@veewee well, I removed the composer cache and tried one more time and I still get the error:

```
rasta@Rasta ~/tmp • git clone https://github.com/better-serializer/better-serializer.git                                                                                                                                                                                                                                                             21:16  rasta@Rasta

Cloning into 'better-serializer'...
remote: Counting objects: 4897, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 4897 (delta 8), reused 27 (delta 7), pack-reused 4854
Receiving objects: 100% (4897/4897), 900.67 KiB | 1.25 MiB/s, done.
Resolving deltas: 100% (3178/3178), done.
~/tmp/better-serializer • git checkout faster_than_reflection                                                                                                                                                                                                                                                                                        
Branch 'faster_than_reflection' set up to track remote branch 'faster_than_reflection' from 'origin'.
Switched to a new branch 'faster_than_reflection'
~/tmp/better-serializer • composer install -o --no-interaction
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 94 installs, 0 updates, 0 removals
  - Installing psr/container (dev-master 2cc4a01): Cloning 2cc4a01788 from cache
...
symfony/var-dumper suggests installing ext-intl (To show region name in time zone dump)
symfony/var-dumper suggests installing ext-symfony_debug ()
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Generating optimized autoload files

Fatal error: Class 'Doctrine\Common\Collections\ArrayCollection' not found in /Users/rasta/tmp/better-serializer/vendor/phpro/grumphp/src/Collection/ProcessArgumentsCollection.php on line 8
```

I also got the same error in this TravisCI build yesterday: https://travis-ci.org/better-serializer/better-serializer/builds/363539243

**Comment by nullwriter** [comment]
Having this same error

**Comment by Rastusik** [comment]
@veewee are you sure you did everything according to the instructions?

**Comment by veewee** [comment]
Pretty sure yeah :) I'll try again somewhere this week.

**Comment by veewee** [comment]
I was running composer 1.3.1 locally. When I update to the latest version, I also get that error.
It's probably related to a change in composer. To be investigated...

**Comment by veewee** [comment]
Actually: it is related to doctrine/collections dev-master:

This works:
```
composer require --dev phpro/grumphp  doctrine/collections:^1.5
```

This doesn't: 
```
composer require --dev phpro/grumphp  doctrine/collections:dev-master
```

Probably related to this change:
https://github.com/doctrine/collections/compare/v1.5.0...master#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R24

**Comment by Rastusik** [comment]
but the change looks ok IMO, only the PSR-X autoload type changed, which should work both ways identically... isn't there a chance for this to be related to some change  in Composer, since your old Composer worked well?

**Comment by veewee** [comment]
Indeed, I was thinking the same after posting that comment.
I wrote a little script to check from which version of composer it breaks:
https://gist.github.com/veewee/d2b0e2a1327e41458daf4453f8ae61b1

Version 1.4.3 works and 1.5.0 Breaks.

So somewhere in this change:
https://github.com/composer/composer/compare/1.4.3...1.5.0

As you can see in the changelog, they changed something to the autoloading in plugins:

```
 +  * Changed the package install order to ensure that plugins are always installed as soon as possible 
```

I don't know the internals of composer that well, but we should definitely log an issue in their project.

**Comment by dxvargas** [comment]
Adding option `"prefer-stable": true` to `composer.json` avoids this error.

**Comment by pfrenssen** [comment]
This was fixed, but it came back in Composer 1.7.0. It is now fixed again in 1.7.1.

Ref. https://github.com/composer/composer/issues/7516

**Comment by javorszky** [comment]
I'm running composer 1.7.1, and on a clean install, I'm still getting the class not found error.

**Comment by Mte90** [comment]
I can confirm the issue on my projects https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/issues/132 from different users and is happening also locally for me.
Prefer stable in composer fix the issue.

**Comment by rafaelstz** [comment]
In my Bitbucket Pipelines, I had to add the command `composer selfupdate` in order to run it properly.

**Comment by veewee** [comment]
Closing this one since it is a composer related issue.
Feel free to open up a new issue if this error still occurs.
